### ISSUE TITLE
Отвалилась синхронизация словарей по крону

### ISSUE THREAD

**Issue by Koc** [alexkuk/Ak_NovaPoshta#7]
Мне кажется, что они перешли на новую версию API?

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/satin/http/app/code/community/Ak/NovaPoshta/Model/Api/Client.php:88
Stack trace:
#0 /home/satin/http/app/code/community/Ak/NovaPoshta/Model/Api/Client.php(88): SimpleXMLElement->__construct('')
#1 /home/satin/http/app/code/community/Ak/NovaPoshta/Model/Api/Client.php(104): Ak_NovaPoshta_Model_Api_Client->_makeRequest(Array)
#2 /home/satin/http/app/code/community/Ak/NovaPoshta/Model/Import.php(52): Ak_NovaPoshta_Model_Api_Client->getCityWarehouses()
#3 /home/satin/http/shell/novaposhta/import.php(20): Ak_NovaPoshta_Model_Import->run()
#4 /home/satin/http/shell/novaposhta/import.php(27): Mage_Shell_Novaposhta_Import->run()
#5 {main}
  thrown in /home/satin/http/app/code/community/Ak/NovaPoshta/Model/Api/Client.php on line 88
```

**Comment by artmouse** [comment]
С 01.09.2016 Новая почта отключила API 1.0, поэтому если что то делалось на API 1.0 оно уже не работает.

Собственно так и есть на своем пример могу сказать что в корзине по средствам API 1.0 был реализован выбор складов и города и расчет стоимости, увы, все это уже не работает
при попытке синхронизировать склады выдается ошибка

```
Error during synchronization: String could not be parsed as XML
```

а при расчете стоимости корзина подвисает, потому что нет обратной связи от сайта НП.

Этот модуль не поддерживает API 2.0

**Comment by Koc** [comment]
Нет желания обновить модуль?)

**Comment by artmouse** [comment]
Есть желание! ))

**Comment by bigshusha** [comment]
Могу выступить тестером ) Очень жду обновления модуля...
